export const FORM_TYPES = [
    'Epicrisis adultos y pediatria',
    'Admisiones internación adultos',
    'Evolución'
]

export const EPICRISIS_STRUCTURE = ["Nombre", "Apellido", "Historia clinica", "Staff a cargo de la internacion",
    "Motivo de admision", "Antecedentes relevantes", "Evaluacion de internacion", "Estudios realizados",
    "Diagnostico principal de egreso/transferencia", "Diagnostico secundario de egreso/transferencia",
    "Medicaciones al egreso", "Dosis", "Frecuencia", "Duracion",
    "Via", "Dieta", "Medicacion previa del paciente" , "Medicacion previa del paciente suspendida/modifficada",
    "Instrucciones de seguimiento", "Pautas de alarma", "Confeccion de epicrisis"]

export const ADMISSIONS_STRUCTURE = ["Tipo de evaluacion",
    "Edad",
    "Sexo",
    "Raza",
    "Motivo de consulta/ingreso",
    "Enfermedad actual y sus antecedentes",
    "Medicacion que recibe actualmente",
    "Otros datos de medicacion actual",
    "Antecedentes patologicos",
    "Tabaquismo"]

export const EVOLUTION_STRUCTURE = ["Medico a cargo",
    "Mo2vo de internaci\u00f3n",
    "Dolor",
    "Diuresis",
    "Par\u00e1metros hemodin\u00e1micos y de perfusi\u00f3n",
    "SpO2",
    "Alimentaci\u00f3n",
    "Catarsis",
    "Pro\ufb01laxis para hemorragia digestiva",
    "Disfunci\u00f3n renal",
    "Control de glucemia",
    "ATB y d\u00edas de ATB",
    "Cul2vos",
    "Aislamiento",
    "Transfusi\u00f3n",
    "Pro\ufb01laxis de TVP",
    "Accesos vasculares",
    "Ulceras por presi\u00f3n",
    "Laboratorio",
    "Otros estudios",
    "Acciones educa2vas implementadas",
    "Impresi\u00f3n diagn\u00f3s2ca",
    "Diagn\u00f3s2cos diferenciales",
    "Interpretaci\u00f3n de diagn\u00f3s2cos",
    "Permanece internado en",
    "Debido a",
    "El paciente requiere intervenciones con \ufb01n",
    "Se es2ma como fecha probable de alta o traslado",
    "Problemas para la con2nuidad en la atenci\u00f3n",
    "Posibles necesidades y requerimientos al egreso",
    "Decisiones tomadas en reuniones mul2disciplinarias",
    "Neurol\u00f3gico",
    "Cardiovascular",
    "Asistencia kin\u00e9sica motriz",
    "Respiratorio",
    "AKR",
    "Gastrointes2nal",
    "Genitourinario",
    "Infectol\u00f3gico",
    "Hematol\u00f3gico",
    "Medio interno, \ufb02uidos, glucemias o endocrino",
    "Manejo del dolor",
    "Soporte vital avanzado",
    "Acciones educa2vas a implementar",
    "Aspectos psicosociales, culturales y religiosos que puedan afectar la atenci\u00f3n",
    "Informe que se le brinda a la familia",
    "Necesidad de interconsultas o reuniones interdisciplinarias, reuniones con la familia, evoluci\u00f3n por asistente social o salud mental"]

export const STRUCTURE_MAP = {
    [FORM_TYPES[0]]: EPICRISIS_STRUCTURE,
    [FORM_TYPES[1]]: ADMISSIONS_STRUCTURE,
    [FORM_TYPES[2]]: EVOLUTION_STRUCTURE
}
